name: CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # If your build has DB/Flyway integration tests, keep tests off for CI stability.
      # Flip to -DskipTests=false later if/when you provide test containers/secrets.
      - name: Maven build
        run: mvn -B -U -DskipTests=true clean verify

      # Upload NBMs and any app zips produced by nbm-application
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: injurytime-suite-artifacts
          if-no-files-found: warn
          path: |
            **/target/*.nbm
            **/target/*-platform.zip
            **/target/*.zip
            **/target/*.jar

